import type { CSSProperties } from 'react';

// Reused across /admin pages. Keeps the admin UI deliberately plain — no
// custom cursor, no Stage chrome — so it loads fast and is easy to scan.

export const adminStyles: Record<string, CSSProperties> = {
  body: {
    minHeight: '100dvh',
    background: 'var(--bg)',
    color: 'var(--ink)',
    fontFamily: 'var(--sans)',
  },
  shell: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '24px 28px 80px',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    paddingBottom: 18,
    borderBottom: '1px solid var(--rule)',
    marginBottom: 32,
  },
  brand: {
    fontFamily: 'var(--serif)',
    fontSize: 24,
    fontWeight: 380,
    letterSpacing: '-0.02em',
    color: 'var(--ink)',
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'baseline',
    gap: 12,
  },
  brandTag: {
    fontFamily: 'var(--mono)',
    fontSize: 10,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'var(--amber)',
  },
  nav: {
    display: 'flex',
    gap: 22,
    fontFamily: 'var(--mono)',
    fontSize: 11,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  navLink: {
    color: 'var(--ink-3)',
    textDecoration: 'none',
    paddingBottom: 4,
    borderBottom: '1px solid transparent',
    transition: 'color 200ms, border-color 200ms',
  },
  navLinkActive: {
    color: 'var(--amber)',
    borderBottom: '1px solid var(--amber)',
  },
  pageTitle: {
    fontFamily: 'var(--serif)',
    fontSize: 38,
    letterSpacing: '-0.025em',
    fontWeight: 380,
    margin: '0 0 24px',
  },
  card: {
    border: '1px solid var(--rule)',
    borderRadius: 12,
    background: 'var(--bg-2)',
    padding: 20,
  },
  statRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: 14,
    marginBottom: 28,
  },
  statLabel: {
    fontFamily: 'var(--mono)',
    fontSize: 10,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: 'var(--ink-4)',
    marginBottom: 8,
  },
  statValue: {
    fontFamily: 'var(--serif)',
    fontSize: 32,
    letterSpacing: '-0.02em',
    color: 'var(--amber)',
    fontWeight: 360,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: 14,
  },
  th: {
    textAlign: 'left' as const,
    padding: '12px 14px',
    borderBottom: '1px solid var(--rule-strong)',
    fontFamily: 'var(--mono)',
    fontSize: 10,
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-4)',
  },
  td: {
    padding: '14px 14px',
    borderBottom: '1px solid var(--rule)',
    verticalAlign: 'top' as const,
  },
  input: {
    background: 'var(--bg)',
    border: '1px solid var(--rule-strong)',
    borderRadius: 6,
    color: 'var(--ink)',
    padding: '8px 10px',
    fontSize: 14,
    fontFamily: 'var(--sans)',
    outline: 'none',
    width: '100%',
  },
  textarea: {
    background: 'var(--bg)',
    border: '1px solid var(--rule-strong)',
    borderRadius: 6,
    color: 'var(--ink)',
    padding: '8px 10px',
    fontSize: 14,
    fontFamily: 'var(--sans)',
    outline: 'none',
    width: '100%',
    minHeight: 80,
    resize: 'vertical' as const,
  },
  button: {
    background: 'var(--amber)',
    color: '#14151B',
    border: 'none',
    borderRadius: 6,
    padding: '8px 16px',
    fontSize: 12,
    fontFamily: 'var(--mono)',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    fontWeight: 600,
  },
  ghostButton: {
    background: 'transparent',
    color: 'var(--ink-3)',
    border: '1px solid var(--rule-strong)',
    borderRadius: 6,
    padding: '8px 16px',
    fontSize: 12,
    fontFamily: 'var(--mono)',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
  },
};
